zk:
  springboot-packaging: war

spring:
  main:
    allow-bean-definition-overriding: true

  autoconfigure:
    exclude:
      - org.springframework.boot.autoconfigure.jdbc.DataSourceAutoConfiguration
      - org.springframework.boot.autoconfigure.jdbc.DataSourceTransactionManagerAutoConfiguration

  profiles:
    active: basic-auth

datasource:
  cash:
    username: "@dbUsername@"
    password: "@dbPassword@"
    jdbc-url: "@dbUrl@"
    maximum-pool-size: 50

server:
  jetty:
    max-http-form-post-size: 1000000000B
  servlet:
    session:
      timeout: 30m
